### ISSUE TITLE
feat(sync): Add support for Stripe Financial Connections.

### ISSUE THREAD

**Issue by elliotcourant** [monetr/monetr#1490]
monetr has been given access to the [Stripe Financial Connections](https://stripe.com/docs/financial-connections) API. This will allow monetr to provide an alternative to Plaid for some institutions. Though the institution availability is a bit foggy at the moment. 

Stripe has direct connections for OAuth based institutions based on their documentation, and beyond that they are white-labeling MX and Finicity it seems.

I think for a predefined list of institutions that are known good via Stripe, this will be an excellent alternative to Plaid for lock-in as well as just institution availability for customers.

It also may be more accessible for customers who wish to self host (once financial connections is out of private beta at least).

---

### Implementation Steps

- [ ] Need to upgrade Stripe Go SDK to the latest version, including upgrading our API version.
- [ ] Add configuration variables to support Financial Connections, just because a Stripe API key is provided does not mean billing is enabled anymore (local dev), or that it has access to these APIs.
- [ ] Update tables in the DB to reflect the source of data for a link. Right now its generally assumed that a non-manual link comes from Plaid and there are many Plaid specific fields sprinkled throughout the schema. Should these be extracted to Plaid specific tables, tying back to their objects they belong on now? Thus allowing Stripe specific tables to come along?
- [ ] Add API endpoints for initiating a Stripe link.
- [ ] Add background job for processing a Stripe sync via a webhook or from an arbitrary timestamp?
- [ ] Add new webhook types to the stripe webhook endpoint.
- [ ] Add Stripe.js to the frontend, build out a way to initiate the connection there and perform callbacks.
